dataset_root: "/mnt/3d_shuyao/data/real_city/aerial_frames"

train_list: "./data/aerial/train_list.txt"
val_list: "./data/aerial/val_list.txt"

train_n_samples_per_subset: 2000 # total: 13000+
val_n_samples_per_subset: 1.0

sort_frames: False

image_height: 512
image_width: 512

sampling_interval: 1.0